// src/Hr.Core/Entities/JobAnnouncement.cs
using Hr.Core.Enums;

namespace Hr.Core.Entities;

/// <summary>
/// A generated job announcement draft for a Position.
/// A position can have multiple drafts over time; only one should be Published.
/// </summary>
public class JobAnnouncement
{
    public int Id { get; set; }

    public int PositionId { get; set; }
    public Position Position { get; set; } = null!;

    /// <summary>Full markdown text generated by WriteJobDescription.</summary>
    public string DraftText { get; set; } = string.Empty;

    public AnnouncementStatus Status { get; set; } = AnnouncementStatus.Draft;

    /// <summary>When the draft was first generated.</summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    /// <summary>When the compliance check was run against this draft.</summary>
    public DateTime? ComplianceCheckedAt { get; set; }

    /// <summary>
    /// Plain-language summary of the compliance outcome written by the OPMCompliance agent.
    /// Null until UpdateAnnouncementStatus is called.
    /// </summary>
    public string? ComplianceSummary { get; set; }
}
